import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('trails')
export class Trail {
  @autoGeneratedHashKey()
  id: string;

  @rangeKey({ defaultProvider: () => new Date() })
  createdAt: Date;

  @attribute()
  name: string;

  @attribute()
  street: string;

  @attribute()
  city: string;

  @attribute()
  state: string;

  @attribute()
  zip: string;

  @attribute()
  latitude: string;

  @attribute()
  longitude: string;
}
